/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upn.projectofinal.vista;

import edu.upn.projectofinal.Controller.DBConnection;
import edu.upn.projectofinal.Model.PasajeroDto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ivan
 */
public class IngresarPasajeros extends javax.swing.JFrame {

    SimpleDateFormat df;
    int codigo;

    /**
     * Creates new form IngresarPasajeros
     */
    public IngresarPasajeros() {
        initComponents();
        cargarComponentes();
        df = new SimpleDateFormat("dd.MM.yyyy");
    }

    void cargarComponentes() {
        cmbTipoDocumento.addItem(PasajeroDto.Tipo.DNI.toString());
        cmbTipoDocumento.addItem(PasajeroDto.Tipo.PASAPORTE.toString());
    }

    Boolean validar() {
        if (txtNombre.getText().equals("")) {
            return false;
        } else if (txtPaterno.getText().equals("")) {
            return false;
        } else if (txtMaterno.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }
    public void limpiar(){
        txtMail.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtNacimeinto.setText("");
        txtNumero.setText("");
    }
    public PasajeroDto getPasajero()  {
        return new PasajeroDto(DBConnection.getNewId()+1,
                txtNombre.getText(),
                txtPaterno.getText(),
                txtMaterno.getText(),
                PasajeroDto.Tipo.valueOf(cmbTipoDocumento.getSelectedItem().toString()),
                txtNumero.getText(),
                //df.parse(txtNacimeinto.getText()),
                new Date(),
                txtMail.getText(),
                1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNacimeinto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 150));
        setMinimumSize(new java.awt.Dimension(520, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 150, 14);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 50, 100, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 60, 20);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 60, 20);
        getContentPane().add(txtPaterno);
        txtPaterno.setBounds(130, 90, 100, 30);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(350, 290, 60, 24);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(40, 290, 81, 24);

        jLabel4.setText("Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 60, 20);
        getContentPane().add(txtMaterno);
        txtMaterno.setBounds(130, 130, 100, 30);
        getContentPane().add(cmbTipoDocumento);
        cmbTipoDocumento.setBounds(140, 170, 100, 23);

        jLabel5.setText("Tipo de Documento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 110, 20);

        jLabel6.setText("Numero Documento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 130, 20);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(160, 220, 80, 30);

        jLabel7.setText("Mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 90, 40, 14);
        getContentPane().add(txtMail);
        txtMail.setBounds(340, 78, 130, 30);

        jLabel8.setText("Nacimiento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 140, 80, 20);
        getContentPane().add(txtNacimeinto);
        txtNacimeinto.setBounds(340, 130, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        new ListPasajeros().setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validar()) {
            if(DBConnection.InsertPasajero(getPasajero())){
                JOptionPane.showMessageDialog(null, "Exito");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error en los Datos de Entrada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error en los Datos de Entrada");

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPasajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNacimeinto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
